- R/createLink.R
> Fixed bug in createLink()

- R/createBindingConstraint.R
- R/editBindingConstraint.R
- R/updateOptimizationSettings.R
- man/editBindingConstraint.Rd
- man/updateOptimizationSettings.Rd
Evolutions 8.3.2: 
- filtering dans les BC
- plus d'options pour le setting : include-exportmps
> Evolutions 8.3.2

- DESCRIPTION
- NEWS.md
- R/editCluster.R
- vignettes/api-variant-management.Rmd
Fix for case sensitivity in editCluster() API
> Fix for case sensitivity in editCluster() API

- NEWS.md
- R/API.R
Fix opts returned when using createVariant()
> Fix createVariant

- NEWS.md
- R/createCluster.R
warning on group in createCluster is now case insensitive
> fix createCluster

- DESCRIPTION
- NEWS.md
- R/createCluster.R
- R/editCluster.R
- R/playlist.R
- Fixed editClusterRES for mode API
- Fixed getPlaylist and setPlaylist in mode API
- Fixed createClusterRES ts argument in mode API
> Cluster res devs

- R/removeArea.R
> removearea fix links before areas

- R/editLink.R
fixed editLink in API mode for v8.2+
> fixed editLink in API mode

- tests/testthat/helper_init.R
- tests/testthat/test-createCluster.R
- tests/testthat/test-createClusterST.R
- tests/testthat/test-editCluster.R
- tests/testthat/test-editClusterST.R
- tests/testthat/test-writeHydroValues.R
- tests/testthat/test-writeInputTS.R
maj tests v860 with new new template
> templates study v860

- DESCRIPTION
- NEWS.md
- R/playlist.R
- tests/testthat/test-playlist.R
- Minimize the number of queries for setPlaylist() in API mode
> setPlaylist() in API mode optimization

- R/createBindingConstraint.R
add "group" parameter in block api call
> add parameter in block api call

- .github/workflows/R-CMD-check.yaml
- R/createCluster.R
- add to stop CI/CD when NOTES are notified in cmdcheck
- fix code with NOTE
> don't forget to check your local NOTES

- NEWS.md
- R/editArea.R
editArea() in API mode must not delete existing values
> Ant1690 bis

- NEWS.md
- R/createClusterST.R
- R/editClusterST.R
- man/createClusterST.Rd
- man/storage_values_default.Rd
- tests/testthat/test-createClusterST.R
- tests/testthat/test-editClusterST.R
create + edit storage updated to manage v880 parameter + cleaning + tests
> storage paramaters version 8.8.0 

- NEWS.md
- R/removeArea.R
- tests/testthat/test-createCluster.R
Family of functions to read input clusters properties are updated in AntareRead ...
> fix side effects from antaresRead function (readClusterDesc, ...)

- NEWS.md
- R/createBindingConstraint.R
- tests/testthat/test-createBindingConstraint.R
Fix createBindingConstraintBulk() with NULL or mixed values + tests
> createBindingConstraintBulk() 

- .github/workflows/pkgdown.yaml
- DESCRIPTION
- NEWS.md
- R/createClusterST.R
- _pkgdown.yml
- man/createClusterST.Rd
- vignettes/api-variant-management.Rmd
createClusterST() doc updated to describe list parameters
> Documentation

- NEWS.md
- R/API-utils.R
Updated with using 'verbose' parameter (#274 `antaresRead`) to display messages + newsmd
> api_command_execute() 

- NEWS.md
- R/createCluster.R
- R/editCluster.R
- tests/testthat/test-createCluster.R
Use the specific endpoint to create or edit a thermal/renewable cluster
> Use the specific endpoint to create or edit a thermal/renewable cluster

- NEWS.md
- R/createClusterST.R
- man/createClusterST.Rd
- tests/testthat/test-createClusterST.R
- new constraints properties
- new constraintes time series
> createClusterST() updated with constraint part + doc + tests

- R/createClusterST.R
- R/editClusterST.R
- man/createClusterST.Rd
- man/editClusterST.Rd
- tests/testthat/test-editClusterST.R
function is updated with new features : 
- constraints properties
- constraints time series
The folder tree structure is `constraints/<area id>/<cluster id>/additional-constraints.ini`
> editClusterST() for 9.2
